In [8]:
import numpy as np
p = []
p.append('oi')
m = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]], dtype = float)
p.append(m)
m = p.pop()
print(p,'\n',m)

['oi'] 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
L = 2
vertices = [[-L,-L,L],[-L,L,L],[L,-L,L],[L,L,L],[-L,-L,-L],[-L,L,-L],[L,-L,-L],[L,L,-L]]
for i in vertices:
    print(i)
        

[-2, -2, 2]
[-2, 2, 2]
[2, -2, 2]
[2, 2, 2]
[-2, -2, -2]
[-2, 2, -2]
[2, -2, -2]
[2, 2, -2]


In [30]:
for i in (-L,L):
    print(i)

-2
2


In [38]:
import math
x=[2,2]
round(x)
print(float(x))


TypeError: type list doesn't define __round__ method

In [23]:
import numpy as np

#Exemplo de um octaedro como o professor me mandou no slack 
r = 10
count_p = 1
count_m = 2
pi = np.pi

def sphere(quant_p,quant_m):
    n=1
    for j in range(0,quant_p+2):
        theta = pi*j/(quant_p+1) 
        #Neste caso como temos um parelelo temos que quebrar o passo do theta em dois
        for i in range(0,2*quant_m):
            phi = pi*i/quant_m
            #Aqui na verdade é 2*pi*i/(2*quant_m)

            x = r*np.cos(phi)*np.sin(theta)
            y = r*np.sin(theta)*np.sin(phi)
            z = r*np.cos(theta)

            print(n,'°',' point','\nx = ',x,'\ny = ',y,'\nz = ',z,'\n')
            n+=1

            #Verifica se são os polos para não calcular pontos a mais
            if theta == 0 or theta == pi: 
                break

sphere(count_p,count_m)


1 °  point 
x =  0.0 
y =  0.0 
z =  10.0 

2 °  point 
x =  10.0 
y =  0.0 
z =  6.123233995736766e-16 

3 °  point 
x =  6.123233995736766e-16 
y =  10.0 
z =  6.123233995736766e-16 

4 °  point 
x =  -10.0 
y =  1.2246467991473533e-15 
z =  6.123233995736766e-16 

5 °  point 
x =  -1.8369701987210296e-15 
y =  -10.0 
z =  6.123233995736766e-16 

6 °  point 
x =  1.2246467991473533e-15 
y =  0.0 
z =  -10.0 



In [16]:
for i in range(1,3):
    print(i)

1
2


In [13]:
v = [0,1,2,3,0,1,2,3]
print(v[:4],v[4:8])

[0, 1, 2, 3] [0, 1, 2, 3]


In [15]:
import numpy as np

def sphere(r,quant_p,quant_m):
    pi = np.pi
    sphere_points = []
    for j in range(0,quant_p+2):
        theta = pi*j/(quant_p+1) 
        #Neste caso como temos um parelelo temos que quebrar o passo do theta em dois
        for i in range(0,2*quant_m):
            phi = pi*i/quant_m
            #Aqui na verdade é 2*pi*i/(2*quant_m)

            x = r*np.cos(phi)*np.sin(theta)
            y = r*np.sin(theta)*np.sin(phi)
            z = r*np.cos(theta)

            sphere_points.append([x,y,z])

            #Verifica se são os polos para não calcular pontos a mais
            if theta == 0 or theta == pi: 
                break
    return sphere_points

sphere_point = sphere(10,1,2)
print(sphere_point,len(sphere_point))

[[0.0, 0.0, 10.0], [10.0, 0.0, 6.123233995736766e-16], [6.123233995736766e-16, 10.0, 6.123233995736766e-16], [-10.0, 1.2246467991473533e-15, 6.123233995736766e-16], [-1.8369701987210296e-15, -10.0, 6.123233995736766e-16], [1.2246467991473533e-15, 0.0, -10.0]] 6


In [46]:
v = [0,1,2,3,4,5]

for i in range(1,5):
    print(v[i])
print('\n')
for i in range(2,6):    
    print(v[len(v)-i])

1
2
3
4


4
3
2
1


In [79]:
v = [0,[1,2,3,4],[8,9,10,11],5]

for i in range(1,len(v)-2):
    for j in range(0,4):
        v = v    
        #print(v[i][j],v[i+1][j])
    #print('\n')
for i in range(1,2):
    print(v[i][0:4])

for j in range(0,2):
    for i in range(1,3):
        print(v[i][j])
    for i in range(1,3):
        print(v[i][j+2])
    print('\n')    

[1, 2, 3, 4]
1
8
3
10


2
9
4
11




In [30]:
v = [0,1,2,3,4,5,6,7,8,9]
p = []
for i in range(1,len(v)-1,3):
    p.append([v[i],v[i+1],v[i+2]])
print(p)

for i in range(-1,len(p)-1):
    print(p[i],p[i+1])

n = [0,[[1,2],3,4],[5,6,7,8],9]
p.append(n[1][0])
#print(p)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[7, 8, 9] [1, 2, 3]
[1, 2, 3] [4, 5, 6]
[4, 5, 6] [7, 8, 9]


In [70]:
L = 1

vertices = [[-L,-L,L],[-L,L,L],[L,L,L],[L,-L,L],[-L,-L,-L],[-L,L,-L],[L,L,-L],[L,-L,-L]]
p=vertices[:4]
print(p[0][2])        

1


In [73]:
for i in range(1,3):
    print(i)

1
2


In [42]:
import numpy as np

def sphere(r,quant_m,quant_p):
    pi = np.pi
    #Points of sphere from de north pole, parallel by parallel, to south pole
    sphere_points = []
    #Join the points from a parallel to then be add as a element in the sphere_points
    intermediary = [] 
    for j in range(0,quant_p+2):
        theta = pi*j/(quant_p+1) 
        #print(theta,'o')
        for i in range(0,2*quant_m):
            phi = pi*i/quant_m
            #print(phi,phi-pi)
            #Aqui na verdade é 2*pi*i/(2*quant_m)

            x = int(r*np.cos(phi)*np.sin(theta))
            y = int(r*np.sin(theta)*np.sin(phi))
            z = int(r*np.cos(theta))

            intermediary.append([x,y,z])
            
            #Make the interruption of the loop if it was the pole 
            if theta == 0 or theta == pi: 
                break
        #Adiciona um elemento com os pontos de um paralelo e limpa o intermediary
        sphere_points.append(intermediary)
        intermediary = []
    return sphere_points

sphere_point = sphere(10,3,2)
print(sphere_point,len(sphere_point),'\n')
for j in range(0,3):
    s=[]
    s.append(sphere_point[0][0])
    for k in range(1, 3):
        s.append(sphere_point[k][j])
    s.append(sphere_point[-1][0])
    for k in range(3, 0,-1):
        s.append(sphere_point[k][j+3])
    print(s)

[[[0, 0, 10]], [[8, 0, 5], [4, 7, 5], [-4, 7, 5], [-8, 0, 5], [-4, -7, 5], [4, -7, 5]], [[8, 0, -4], [4, 7, -4], [-4, 7, -4], [-8, 0, -4], [-4, -7, -4], [4, -7, -4]], [[0, 0, -10]]] 4 



IndexError: list index out of range

In [9]:
import numpy as np

transform_matrix = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,-500],[0,0,0,1]], dtype = float)
p = transform_matrix.dot([float(-100),float(-100),float(-100),1])

print(p)

[-100. -100. -600.    1.]


In [16]:
f = [200.0] 
n = int(f[0])
print(type(n),n,f)

<class 'int'> 200 [200.0]


In [61]:
L = 1

for j in (-L,L):
    for i in (1,-1):
        #print(L,i*L,j,-L,-i*L,j)

        #print(L,j,i*L,-L,j,-i*L)

        print(j,L,i*L,j,-L,-i*L)
        
        print('\n')

-1 1 1 -1 -1 -1


-1 1 -1 -1 -1 1


1 1 1 1 -1 -1


1 1 -1 1 -1 1


